name: release-please

on:
  push:
    branches:
      - main

permissions: write-all

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - name: checkout
        uses: actions/checkout@v4
      - name: release-please
        id: release-please
        uses: googleapis/release-please-action@v4
      - name: setup bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version-file: .tool-versions
      - name: setup bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version-file: .tool-versions
      - name: parse
        id: parse
        uses: ./actions/release-matrix
    outputs:
      releases-created: ${{ steps.parse.outputs.releases-created }}
      packages: ${{ steps.release-please.outputs.releases }}

  # release:
  #   name: "[${{ matrix.package }}] Release"
  #   runs-on: ubuntu-latest
  #   needs: [release-please]
  #   if: fromJSON(needs.release-please.outputs.releases-created)
  #   matrix:
  #     fail-fast: false
  #     packages: fromJSON(needs.release-please.outputs.packages)
  #   steps:
  #     - name: the details
  #       run: |
  #         echo "
